version: '3.7'

services:
  sns-backend:
    container_name: sns-api
    build:
      context: backend
    ports:
      - ${NODE_PORT_EXTERN}:${NODE_PORT_INTERN}
    command: npm run start
    env_file:
      - .env
      - backend/environments/node/${NODE_ENV}.env
      - backend/environments/mysql/${MYSQL_ENV}.env
    networks:
      - back-end
    depends_on:
      - sns-mysql

  sns-frontend:
    container_name: sns-frontend
    build:
      context: frontend
    ports:
      - ${ANGULAR_PORT_EXTERN}:${ANGULAR_PORT_INTERN}
    env_file:
      - .env
    depends_on:
      - sns-backend

  sns-mysql:
    container_name: sns-mysql
    image: mariadb:10.7.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file:
      - backend/.env
      - backend/environments/node/${NODE_ENV}.env
      - backend/environments/mysql/${MYSQL_ENV}.env
    networks:
      - back-end
    ports:
      - ${MYSQL_PORT_EXTERN}:${MYSQL_PORT_INTERN}

  sns-adminer:
    container_name: sns-adminer
    image: adminer
    depends_on:
      - sns-mysql
    networks:
      - back-end
    ports:
      - ${ADMINER_PORT_EXTERN}:${ADMINER_PORT_INTERN}

networks:
  back-end:
